// Generated by Wrangler
// After adding bindings to `wrangler.toml`, regenerate this interface via `npm run cf-typegen`
interface Env {
	newsdataAPI: string;
	UPSTASH_TOKEN: string | undefined;
	UPSTASH_INDEX_URL: string | undefined;
	KV: KVNamespace;
	AI: unknown;
}
